package StringOperations;


/**
* StringOperations/Reverser.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Reverser.idl
* Wednesday, May 7, 2025 10:30:57 AM PDT
*/

public interface Reverser extends ReverserOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Reverser
